
version: '3'
services:
  prometheus:
    container_name: Prometheus
    image: prom/prometheus
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: always
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
  grafana:
    container_name: Grafana
    image: grafana/grafana
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"
  zipkin:
    container_name: Zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: always
    ports:
      - "9411:9411"
  postgres:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


